sudo: false
language: cpp
git:
  submodules: false

compiler:
  - gcc
#  - clang

before_install:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then openssl aes-256-cbc -K $encrypted_63c9d3fcdbeb_key -iv $encrypted_63c9d3fcdbeb_iv -in .dropbox_uploader.enc -out .dropbox_uploader -d; fi
  - export PATH=$HOME/bin:$PATH
  - wget cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.sh
  - echo y | $SHELL cmake-3.3.2-Linux-x86_64.sh --prefix=$HOME --exclude-subdir

install:
  - export COMPILER_NAME=$CC
  - if [ "$CXX" = "g++" ]; then export CXX="$(which g++-5)" CC="$(which gcc-5)"; fi
#  - if [ "$CXX" = "clang++" ]; then export CXX="$(which clang++-3.7)" CC="$(which clang-3.7)"; fi
  - echo $CXX

before_script :
  - make deps

script:
  - make all

after_success:
  - if [ -n "$TRAVIS_PULL_REQUEST" ]; then ./deploy.sh; fi

addons:
  apt:
    sources:
      - r-packages-precise
#      - llvm-toolchain-precise
      - ubuntu-toolchain-r-test
#      - llvm-toolchain-precise-3.7
    packages:
      - g++-5
      - python3
#      - clang-3.7
