sudo: false
language: cpp
git:
  submodules: false

compiler:
  - gcc
  - clang

before_install:
  - [ -n "$TRAVIS_PULL_REQUEST" ] && openssl aes-256-cbc -K $encrypted_63c9d3fcdbeb_key -iv $encrypted_63c9d3fcdbeb_iv -in .dropbox_uploader.enc -out .dropbox_uploader -d

install:
  - export COMPILER_NAME=$CC
  - [ "$CXX" = "g++" ] && export CXX=g++-5 CC=gcc-5
  - [ "$CXX" = "clang++" ] && export CXX=clang++-3.6 CC=clang-3.6

before_script :
  - make deps

script:
  - make all

after_success:
  - [ -n "$TRAVIS_PULL_REQUEST" ] && ./deploy.sh

addons:
  apt:
    sources:
      - r-packages-precise
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.6
    packages:
      - g++-5
      - clang-3.6
